name: weather_app_k
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  flutter_bloc: ^8.1.6
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

# This section should be at the root level, not nested under dev_dependencies
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Weather_App.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
